development:
  cloud_name: CLOUDINARY_NAME
  api_key: CLOUDINARY_API_KEY
  api_secret: CLOUDINARY_API_SECRET
  enhance_image_tag: true
  static_file_support: false
  secure: true

production:
  cloud_name: CLOUDINARY_NAME
  api_key: CLOUDINARY_API_KEY
  api_secret: CLOUDINARY_API_SECRET
  enhance_image_tag: true
  static_file_support: true
  secure: true
