INSERT INTO cities (name, states_id, created_at, updated_at)
VALUES
  ('Abaíra', 1, 'now', 'now'),
  ('Abaré', 1, 'now', 'now'),
  ('Acajutiba', 1, 'now', 'now'),
  ('Adustina', 1, 'now', 'now'),
  ('Água Fria', 1, 'now', 'now'),
  ('Érico Cardoso', 1, 'now', 'now'),
  ('Aiquara', 1, 'now', 'now'),
  ('Alagoinhas', 1, 'now', 'now'),
  ('Alcobaça', 1, 'now', 'now'),
  ('Almadina', 1, 'now', 'now'),
  ('Amargosa', 1, 'now', 'now'),
  ('Amélia Rodrigues', 1, 'now', 'now'),
  ('América Dourada', 1, 'now', 'now'),
  ('Anagé', 1, 'now', 'now'),
  ('Andaraí', 1, 'now', 'now'),
  ('Andorinha', 1, 'now', 'now'),
  ('Angical', 1, 'now', 'now'),
  ('Anguera', 1, 'now', 'now'),
  ('Antas', 1, 'now', 'now'),
  ('Antônio Cardoso', 1, 'now', 'now'),
  ('Antônio Gonçalves', 1, 'now', 'now'),
  ('Aporá', 1, 'now', 'now'),
  ('Apuarema', 1, 'now', 'now'),
  ('Aracatu', 1, 'now', 'now'),
  ('Araçás', 1, 'now', 'now'),
  ('Araci', 1, 'now', 'now'),
  ('Aramari', 1, 'now', 'now'),
  ('Arataca', 1, 'now', 'now'),
  ('Aratuípe', 1, 'now', 'now'),
  ('Aurelino Leal', 1, 'now', 'now'),
  ('Baianópolis', 1, 'now', 'now'),
  ('Baixa Grande', 1, 'now', 'now'),
  ('Banzaê', 1, 'now', 'now'),
  ('Barra', 1, 'now', 'now'),
  ('Barra da Estiva', 1, 'now', 'now'),
  ('Barra do Choça', 1, 'now', 'now'),
  ('Barra do Mendes', 1, 'now', 'now'),
  ('Barra do Rocha', 1, 'now', 'now'),
  ('Barreiras', 1, 'now', 'now'),
  ('Barro Alto', 1, 'now', 'now'),
  ('Barrocas', 1, 'now', 'now'),
  ('Barro Preto', 1, 'now', 'now'),
  ('Belmonte', 1, 'now', 'now'),
  ('Belo Campo', 1, 'now', 'now'),
  ('Biritinga', 1, 'now', 'now'),
  ('Boa Nova', 1, 'now', 'now'),
  ('Boa Vista do Tupim', 1, 'now', 'now'),
  ('Bom Jesus da Lapa', 1, 'now', 'now'),
  ('Bom Jesus da Serra', 1, 'now', 'now'),
  ('Boninal', 1, 'now', 'now'),
  ('Bonito', 1, 'now', 'now'),
  ('Boquira', 1, 'now', 'now'),
  ('Botuporã', 1, 'now', 'now'),
  ('Brejões', 1, 'now', 'now'),
  ('Brejolândia', 1, 'now', 'now'),
  ('Brotas de Macaúbas', 1, 'now', 'now'),
  ('Brumado', 1, 'now', 'now'),
  ('Buerarema', 1, 'now', 'now'),
  ('Buritirama', 1, 'now', 'now'),
  ('Caatiba', 1, 'now', 'now'),
  ('Cabaceiras do Paraguaçu', 1, 'now', 'now'),
  ('Cachoeira', 1, 'now', 'now'),
  ('Caculé', 1, 'now', 'now'),
  ('Caém', 1, 'now', 'now'),
  ('Caetanos', 1, 'now', 'now'),
  ('Caetité', 1, 'now', 'now'),
  ('Cafarnaum', 1, 'now', 'now'),
  ('Cairu', 1, 'now', 'now'),
  ('Caldeirão Grande', 1, 'now', 'now'),
  ('Camacan', 1, 'now', 'now'),
  ('Camaçari', 1, 'now', 'now'),
  ('Camamu', 1, 'now', 'now'),
  ('Campo Alegre de Lourdes', 1, 'now', 'now'),
  ('Campo Formoso', 1, 'now', 'now'),
  ('Canápolis', 1, 'now', 'now'),
  ('Canarana', 1, 'now', 'now'),
  ('Canavieiras', 1, 'now', 'now'),
  ('Candeal', 1, 'now', 'now'),
  ('Candeias', 1, 'now', 'now'),
  ('Candiba', 1, 'now', 'now'),
  ('Cândido Sales', 1, 'now', 'now'),
  ('Cansanção', 1, 'now', 'now'),
  ('Canudos', 1, 'now', 'now'),
  ('Capela do Alto Alegre', 1, 'now', 'now'),
  ('Capim Grosso', 1, 'now', 'now'),
  ('Caraíbas', 1, 'now', 'now'),
  ('Caravelas', 1, 'now', 'now'),
  ('Cardeal da Silva', 1, 'now', 'now'),
  ('Carinhanha', 1, 'now', 'now'),
  ('Casa Nova', 1, 'now', 'now'),
  ('Castro Alves', 1, 'now', 'now'),
  ('Catolândia', 1, 'now', 'now'),
  ('Catu', 1, 'now', 'now'),
  ('Caturama', 1, 'now', 'now'),
  ('Central', 1, 'now', 'now'),
  ('Chorrochó', 1, 'now', 'now'),
  ('Cícero Dantas', 1, 'now', 'now'),
  ('Cipó', 1, 'now', 'now'),
  ('Coaraci', 1, 'now', 'now'),
  ('Cocos', 1, 'now', 'now'),
  ('Conceição da Feira', 1, 'now', 'now'),
  ('Conceição do Almeida', 1, 'now', 'now'),
  ('Conceição do Coité', 1, 'now', 'now'),
  ('Conceição do Jacuípe', 1, 'now', 'now'),
  ('Conde', 1, 'now', 'now'),
  ('Condeúba', 1, 'now', 'now'),
  ('Contendas do Sincorá', 1, 'now', 'now'),
  ('Coração de Maria', 1, 'now', 'now'),
  ('Cordeiros', 1, 'now', 'now'),
  ('Coribe', 1, 'now', 'now'),
  ('Coronel João Sá', 1, 'now', 'now'),
  ('Correntina', 1, 'now', 'now'),
  ('Cotegipe', 1, 'now', 'now'),
  ('Cravolândia', 1, 'now', 'now'),
  ('Crisópolis', 1, 'now', 'now'),
  ('Cristópolis', 1, 'now', 'now'),
  ('Cruz das Almas', 1, 'now', 'now'),
  ('Curaçá', 1, 'now', 'now'),
  ('Dário Meira', 1, 'now', 'now'),
  ('Dias d Ávila', 1, 'now', 'now'),
  ('Dom Basílio', 1, 'now', 'now'),
  ('Dom Macedo Costa', 1, 'now', 'now'),
  ('Elísio Medrado', 1, 'now', 'now'),
  ('Encruzilhada', 1, 'now', 'now'),
  ('Entre Rios', 1, 'now', 'now'),
  ('Esplanada', 1, 'now', 'now'),
  ('Euclides da Cunha', 1, 'now', 'now'),
  ('Eunápolis', 1, 'now', 'now'),
  ('Fátima', 1, 'now', 'now'),
  ('Feira da Mata', 1, 'now', 'now'),
  ('Feira de Santana', 1, 'now', 'now'),
  ('Filadélfia', 1, 'now', 'now'),
  ('Firmino Alves', 1, 'now', 'now'),
  ('Floresta Azul', 1, 'now', 'now'),
  ('Formosa do Rio Preto', 1, 'now', 'now'),
  ('Gandu', 1, 'now', 'now'),
  ('Gavião', 1, 'now', 'now'),
  ('Gentio do Ouro', 1, 'now', 'now'),
  ('Glória', 1, 'now', 'now'),
  ('Gongogi', 1, 'now', 'now'),
  ('Governador Mangabeira', 1, 'now', 'now'),
  ('Guajeru', 1, 'now', 'now'),
  ('Guanambi', 1, 'now', 'now'),
  ('Guaratinga', 1, 'now', 'now'),
  ('Heliópolis', 1, 'now', 'now'),
  ('Iaçu', 1, 'now', 'now'),
  ('Ibiassucê', 1, 'now', 'now'),
  ('Ibicaraí', 1, 'now', 'now'),
  ('Ibicoara', 1, 'now', 'now'),
  ('Ibicuí', 1, 'now', 'now'),
  ('Ibipeba', 1, 'now', 'now'),
  ('Ibipitanga', 1, 'now', 'now'),
  ('Ibiquera', 1, 'now', 'now'),
  ('Ibirapitanga', 1, 'now', 'now'),
  ('Ibirapuã', 1, 'now', 'now'),
  ('Ibirataia', 1, 'now', 'now'),
  ('Ibitiara', 1, 'now', 'now'),
  ('Ibititá', 1, 'now', 'now'),
  ('Ibotirama', 1, 'now', 'now'),
  ('Ichu', 1, 'now', 'now'),
  ('Igaporã', 1, 'now', 'now'),
  ('Igrapiúna', 1, 'now', 'now'),
  ('Iguaí', 1, 'now', 'now'),
  ('Ilhéus', 1, 'now', 'now'),
  ('Inhambupe', 1, 'now', 'now'),
  ('Ipecaetá', 1, 'now', 'now'),
  ('Ipiaú', 1, 'now', 'now'),
  ('Ipirá', 1, 'now', 'now'),
  ('Ipupiara', 1, 'now', 'now'),
  ('Irajuba', 1, 'now', 'now'),
  ('Iramaia', 1, 'now', 'now'),
  ('Iraquara', 1, 'now', 'now'),
  ('Irará', 1, 'now', 'now'),
  ('Irecê', 1, 'now', 'now'),
  ('Itabela', 1, 'now', 'now'),
  ('Itaberaba', 1, 'now', 'now'),
  ('Itabuna', 1, 'now', 'now'),
  ('Itacaré', 1, 'now', 'now'),
  ('Itaeté', 1, 'now', 'now'),
  ('Itagi', 1, 'now', 'now'),
  ('Itagibá', 1, 'now', 'now'),
  ('Itagimirim', 1, 'now', 'now'),
  ('Itaguaçu da Bahia', 1, 'now', 'now'),
  ('Itaju do Colônia', 1, 'now', 'now'),
  ('Itajuípe', 1, 'now', 'now'),
  ('Itamaraju', 1, 'now', 'now'),
  ('Itamari', 1, 'now', 'now'),
  ('Itambé', 1, 'now', 'now'),
  ('Itanagra', 1, 'now', 'now'),
  ('Itanhém', 1, 'now', 'now'),
  ('Itaparica', 1, 'now', 'now'),
  ('Itapé', 1, 'now', 'now'),
  ('Itapebi', 1, 'now', 'now'),
  ('Itapetinga', 1, 'now', 'now'),
  ('Itapicuru', 1, 'now', 'now'),
  ('Itapitanga', 1, 'now', 'now'),
  ('Itaquara', 1, 'now', 'now'),
  ('Itarantim', 1, 'now', 'now'),
  ('Itatim', 1, 'now', 'now'),
  ('Itiruçu', 1, 'now', 'now'),
  ('Itiúba', 1, 'now', 'now'),
  ('Itororó', 1, 'now', 'now'),
  ('Ituaçu', 1, 'now', 'now'),
  ('Ituberá', 1, 'now', 'now'),
  ('Iuiu', 1, 'now', 'now'),
  ('Jaborandi', 1, 'now', 'now'),
  ('Jacaraci', 1, 'now', 'now'),
  ('Jacobina', 1, 'now', 'now'),
  ('Jaguaquara', 1, 'now', 'now'),
  ('Jaguarari', 1, 'now', 'now'),
  ('Jaguaripe', 1, 'now', 'now'),
  ('Jandaíra', 1, 'now', 'now'),
  ('Jequié', 1, 'now', 'now'),
  ('Jeremoabo', 1, 'now', 'now'),
  ('Jiquiriçá', 1, 'now', 'now'),
  ('Jitaúna', 1, 'now', 'now'),
  ('João Dourado', 1, 'now', 'now'),
  ('Juazeiro', 1, 'now', 'now'),
  ('Jucuruçu', 1, 'now', 'now'),
  ('Jussara', 1, 'now', 'now'),
  ('Jussari', 1, 'now', 'now'),
  ('Jussiape', 1, 'now', 'now'),
  ('Lafaiete Coutinho', 1, 'now', 'now'),
  ('Lagoa Real', 1, 'now', 'now'),
  ('Laje', 1, 'now', 'now'),
  ('Lajedão', 1, 'now', 'now'),
  ('Lajedinho', 1, 'now', 'now'),
  ('Lajedo do Tabocal', 1, 'now', 'now'),
  ('Lamarão', 1, 'now', 'now'),
  ('Lapão', 1, 'now', 'now'),
  ('Lauro de Freitas', 1, 'now', 'now'),
  ('Lençóis', 1, 'now', 'now'),
  ('Licínio de Almeida', 1, 'now', 'now'),
  ('Livramento de Nossa Senhora', 1, 'now', 'now'),
  ('Luís Eduardo Magalhães', 1, 'now', 'now'),
  ('Macajuba', 1, 'now', 'now'),
  ('Macarani', 1, 'now', 'now'),
  ('Macaúbas', 1, 'now', 'now'),
  ('Macururé', 1, 'now', 'now'),
  ('Madre de Deus', 1, 'now', 'now'),
  ('Maetinga', 1, 'now', 'now'),
  ('Maiquinique', 1, 'now', 'now'),
  ('Mairi', 1, 'now', 'now'),
  ('Malhada', 1, 'now', 'now'),
  ('Malhada de Pedras', 1, 'now', 'now'),
  ('Manoel Vitorino', 1, 'now', 'now'),
  ('Mansidão', 1, 'now', 'now'),
  ('Maracás', 1, 'now', 'now'),
  ('Maragogipe', 1, 'now', 'now'),
  ('Maraú', 1, 'now', 'now'),
  ('Marcionílio Souza', 1, 'now', 'now'),
  ('Mascote', 1, 'now', 'now'),
  ('Mata de São João', 1, 'now', 'now'),
  ('Matina', 1, 'now', 'now'),
  ('Medeiros Neto', 1, 'now', 'now'),
  ('Miguel Calmon', 1, 'now', 'now'),
  ('Milagres', 1, 'now', 'now'),
  ('Mirangaba', 1, 'now', 'now'),
  ('Mirante', 1, 'now', 'now'),
  ('Monte Santo', 1, 'now', 'now'),
  ('Morpará', 1, 'now', 'now'),
  ('Morro do Chapéu', 1, 'now', 'now'),
  ('Mortugaba', 1, 'now', 'now'),
  ('Mucugê', 1, 'now', 'now'),
  ('Mucuri', 1, 'now', 'now'),
  ('Mulungu do Morro', 1, 'now', 'now'),
  ('Mundo Novo', 1, 'now', 'now'),
  ('Muniz Ferreira', 1, 'now', 'now'),
  ('Muquém do São Francisco', 1, 'now', 'now'),
  ('Muritiba', 1, 'now', 'now'),
  ('Mutuípe', 1, 'now', 'now'),
  ('Nazaré', 1, 'now', 'now'),
  ('Nilo Peçanha', 1, 'now', 'now'),
  ('Nordestina', 1, 'now', 'now'),
  ('Nova Canaã', 1, 'now', 'now'),
  ('Nova Fátima', 1, 'now', 'now'),
  ('Nova Ibiá', 1, 'now', 'now'),
  ('Nova Itarana', 1, 'now', 'now'),
  ('Nova Redenção', 1, 'now', 'now'),
  ('Nova Soure', 1, 'now', 'now'),
  ('Nova Viçosa', 1, 'now', 'now'),
  ('Novo Horizonte', 1, 'now', 'now'),
  ('Novo Triunfo', 1, 'now', 'now'),
  ('Olindina', 1, 'now', 'now'),
  ('Oliveira dos Brejinhos', 1, 'now', 'now'),
  ('Ouriçangas', 1, 'now', 'now'),
  ('Ourolândia', 1, 'now', 'now'),
  ('Palmas de Monte Alto', 1, 'now', 'now'),
  ('Palmeiras', 1, 'now', 'now'),
  ('Paramirim', 1, 'now', 'now'),
  ('Paratinga', 1, 'now', 'now'),
  ('Paripiranga', 1, 'now', 'now'),
  ('Pau Brasil', 1, 'now', 'now'),
  ('Paulo Afonso', 1, 'now', 'now'),
  ('Pé de Serra', 1, 'now', 'now'),
  ('Pedrão', 1, 'now', 'now'),
  ('Pedro Alexandre', 1, 'now', 'now'),
  ('Piatã', 1, 'now', 'now'),
  ('Pilão Arcado', 1, 'now', 'now'),
  ('Pindaí', 1, 'now', 'now'),
  ('Pindobaçu', 1, 'now', 'now'),
  ('Pintadas', 1, 'now', 'now'),
  ('Piraí do Norte', 1, 'now', 'now'),
  ('Piripá', 1, 'now', 'now'),
  ('Piritiba', 1, 'now', 'now'),
  ('Planaltino', 1, 'now', 'now'),
  ('Planalto', 1, 'now', 'now'),
  ('Poções', 1, 'now', 'now'),
  ('Pojuca', 1, 'now', 'now'),
  ('Ponto Novo', 1, 'now', 'now'),
  ('Porto Seguro', 1, 'now', 'now'),
  ('Potiraguá', 1, 'now', 'now'),
  ('Prado', 1, 'now', 'now'),
  ('Presidente Dutra', 1, 'now', 'now'),
  ('Presidente Jânio Quadros', 1, 'now', 'now'),
  ('Presidente Tancredo Neves', 1, 'now', 'now'),
  ('Queimadas', 1, 'now', 'now'),
  ('Quijingue', 1, 'now', 'now'),
  ('Quixabeira', 1, 'now', 'now'),
  ('Rafael Jambeiro', 1, 'now', 'now'),
  ('Remanso', 1, 'now', 'now'),
  ('Retirolândia', 1, 'now', 'now'),
  ('Riachão das Neves', 1, 'now', 'now'),
  ('Riachão do Jacuípe', 1, 'now', 'now'),
  ('Riacho de Santana', 1, 'now', 'now'),
  ('Ribeira do Amparo', 1, 'now', 'now'),
  ('Ribeira do Pombal', 1, 'now', 'now'),
  ('Ribeirão do Largo', 1, 'now', 'now'),
  ('Rio de Contas', 1, 'now', 'now'),
  ('Rio do Antônio', 1, 'now', 'now'),
  ('Rio do Pires', 1, 'now', 'now'),
  ('Rio Real', 1, 'now', 'now'),
  ('Rodelas', 1, 'now', 'now'),
  ('Ruy Barbosa', 1, 'now', 'now'),
  ('Salinas da Margarida', 1, 'now', 'now'),
  ('Salvador', 1, 'now', 'now'),
  ('Santa Bárbara', 1, 'now', 'now'),
  ('Santa Brígida', 1, 'now', 'now'),
  ('Santa Cruz Cabrália', 1, 'now', 'now'),
  ('Santa Cruz da Vitória', 1, 'now', 'now'),
  ('Santa Inês', 1, 'now', 'now'),
  ('Santaluz', 1, 'now', 'now'),
  ('Santa Luzia', 1, 'now', 'now'),
  ('Santa Maria da Vitória', 1, 'now', 'now'),
  ('Santana', 1, 'now', 'now'),
  ('Santanópolis', 1, 'now', 'now'),
  ('Santa Rita de Cássia', 1, 'now', 'now'),
  ('Santa Terezinha', 1, 'now', 'now'),
  ('Santo Amaro', 1, 'now', 'now'),
  ('Santo Antônio de Jesus', 1, 'now', 'now'),
  ('Santo Estêvão', 1, 'now', 'now'),
  ('São Desidério', 1, 'now', 'now'),
  ('São Domingos', 1, 'now', 'now'),
  ('São Félix', 1, 'now', 'now'),
  ('São Félix do Coribe', 1, 'now', 'now'),
  ('São Felipe', 1, 'now', 'now'),
  ('São Francisco do Conde', 1, 'now', 'now'),
  ('São Gabriel', 1, 'now', 'now'),
  ('São Gonçalo dos Campos', 1, 'now', 'now'),
  ('São José da Vitória', 1, 'now', 'now'),
  ('São José do Jacuípe', 1, 'now', 'now'),
  ('São Miguel das Matas', 1, 'now', 'now'),
  ('São Sebastião do Passé', 1, 'now', 'now'),
  ('Sapeaçu', 1, 'now', 'now'),
  ('Sátiro Dias', 1, 'now', 'now'),
  ('Saubara', 1, 'now', 'now'),
  ('Saúde', 1, 'now', 'now'),
  ('Seabra', 1, 'now', 'now'),
  ('Sebastião Laranjeiras', 1, 'now', 'now'),
  ('Senhor do Bonfim', 1, 'now', 'now'),
  ('Serra do Ramalho', 1, 'now', 'now'),
  ('Sento Sé', 1, 'now', 'now'),
  ('Serra Dourada', 1, 'now', 'now'),
  ('Serra Preta', 1, 'now', 'now'),
  ('Serrinha', 1, 'now', 'now'),
  ('Serrolândia', 1, 'now', 'now'),
  ('Simões Filho', 1, 'now', 'now'),
  ('Sítio do Mato', 1, 'now', 'now'),
  ('Sítio do Quinto', 1, 'now', 'now'),
  ('Sobradinho', 1, 'now', 'now'),
  ('Souto Soares', 1, 'now', 'now'),
  ('Tabocas do Brejo Velho', 1, 'now', 'now'),
  ('Tanhaçu', 1, 'now', 'now'),
  ('Tanque Novo', 1, 'now', 'now'),
  ('Tanquinho', 1, 'now', 'now'),
  ('Taperoá', 1, 'now', 'now'),
  ('Tapiramutá', 1, 'now', 'now'),
  ('Teixeira de Freitas', 1, 'now', 'now'),
  ('Teodoro Sampaio', 1, 'now', 'now'),
  ('Teofilândia', 1, 'now', 'now'),
  ('Teolândia', 1, 'now', 'now'),
  ('Terra Nova', 1, 'now', 'now'),
  ('Tremedal', 1, 'now', 'now'),
  ('Tucano', 1, 'now', 'now'),
  ('Uauá', 1, 'now', 'now'),
  ('Ubaíra', 1, 'now', 'now'),
  ('Ubaitaba', 1, 'now', 'now'),
  ('Ubatã', 1, 'now', 'now'),
  ('Uibaí', 1, 'now', 'now'),
  ('Umburanas', 1, 'now', 'now'),
  ('Una', 1, 'now', 'now'),
  ('Urandi', 1, 'now', 'now'),
  ('Uruçuca', 1, 'now', 'now'),
  ('Utinga', 1, 'now', 'now'),
  ('Valença', 1, 'now', 'now'),
  ('Valente', 1, 'now', 'now'),
  ('Várzea da Roça', 1, 'now', 'now'),
  ('Várzea do Poço', 1, 'now', 'now'),
  ('Várzea Nova', 1, 'now', 'now'),
  ('Varzedo', 1, 'now', 'now'),
  ('Vera Cruz', 1, 'now', 'now'),
  ('Vereda', 1, 'now', 'now'),
  ('Vitória da Conquista', 1, 'now', 'now'),
  ('Wagner', 1, 'now', 'now'),
  ('Wanderley', 1, 'now', 'now'),
  ('Wenceslau Guimarães', 1, 'now', 'now'),
  ('Xique-Xique', 1, 'now', 'now')
;
